import { NEXT_SEO_DEFAULT } from "@/next-seo.config";
import { fetchImage } from "@/utils";
import { getDomain } from "@/utils/getDomain";
import { NextSeo } from "next-seo";

export default async function Head() {
  const seo = {
    title: "Movie | TMDB",
    description: "Movie site free.",
    linkTo: "",
    images: [],
  };
  return (
    <>
      <title>{seo?.title}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      {/* <meta name="description" content="Generated by create next app" /> */}
      {/* <link rel="icon" href="/favicon.ico" /> */}
      <NextSeo
        useAppDir
        title={seo?.title ? seo?.title.substring(0, 70) : "A title of page"}
        description={
          seo?.description
            ? seo?.description.substring(0, 320)
            : "A short description goes here."
        }
        canonical={`${getDomain()}${seo?.linkTo}`}
        openGraph={{
          url: `${getDomain()}${seo?.linkTo}`,
          title: seo?.title.substring(0, 70),
          description: seo?.description
            ? seo?.description.substring(0, 320)
            : "A short description goes here.",
          images:
            seo?.images > 0
              ? seo?.images?.map((load) => ({
                  url: fetchImage(load),
                }))
              : [
                  {
                    url: `${getDomain()}/images/android-chrome-192x192.png`,
                  },
                ],
          site_name: "Webite Name",
          type: "website",
        }}
        twitter={{
          handle: "@handle",
          site: "@site",
          cardType: "summary_large_image",
        }}
      />
    </>
  );
}
