import { NEXT_SEO_DEFAULT } from "@/next-seo.config";
import { NextSeo } from "next-seo";

export default async function Head() {
  return (
    <>
      <title>Movie | TMDB</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <NextSeo {...NEXT_SEO_DEFAULT} useAppDir={true} />;
    </>
  );
}
